apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PROMETHEUS_DS
    url: http://prometheus:9090
    access: proxy
    isDefault: true

  - name: InfluxDB
    type: influxdb
    uid: INFLUXDB_DS
    url: http://influxdb:8086
    database: k6
    access: proxy